name: clean_archi

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
    command: "bash -c \"npm run prisma:migrate && npm run start:dev\""
    

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080

volumes:
  pgdata: